### ISSUE TITLE
Exception with escaped % in parameters

### ISSUE THREAD

**Issue by rchomat** [FriendsOfBehat/CrossContainerExtension#16]
Hi,

Considered I have a parameters.yml with this content : 
```
parameters:
    param1: "testParam1-%%s-%%s"
    param2:
        test1: "test1-%%s-%%s"
        test2: "test2-%%s-%%s"
```

I get this error : 
`The parameter "__symfony__.param1" has a dependency on a non-existent parameter "s-".`

Seems like it comes from the following line which should escape the values before adding in the parameterBag. Indeed, the parameters got by the container are already parsed.
 https://github.com/FriendsOfBehat/CrossContainerExtension/blob/7caf07e036fb2923babf4f962d8c21182140514b/src/CrossContainerProcessor.php#L188
