### ISSUE TITLE
Issue with Symfony 4? (not booted Kernel)

### ISSUE THREAD

**Issue by Kocal** [FriendsOfBehat/CrossContainerExtension#20]
Hey,

So as said in #18, I had a problem to make `CrossContainerExtension` works for Symfony 4. 
In fact, I don't know if it's related to Symfony 4 or if I a mis-configurated the package.. :confused: 

My issue appears when I'm running Behat:

![capture d ecran de 2018-01-24 20-46-42](https://user-images.githubusercontent.com/2103975/35353527-bbf99352-0147-11e8-9e80-b63686ddcb79.png)

It seems `CrossContainerExtension` is not able to access my Kernel's container (it is `null`).

<details>
  <summary>**Here are my files (Click to expand)**</summary>
  
**composer.json**
```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/Kocal/CrossContainerExtension"
    }
  ],
  "require-dev": {
    "friends-of-behat/context-service-extension": "dev-master",
    "friends-of-behat/cross-container-extension": "dev-symfony-4-support",
    "friends-of-behat/symfony-extension": "dev-master"
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "App\\Tests\\": "tests/",
      "Features\\": "features/bootstrap/"
    }
  }
}
```

**behat.yml**
```yml
default:
    suites:
        default:
            contexts_services:
                - features.definitions.user

    extensions:
        FriendsOfBehat\SymfonyExtension:
            kernel:
                class: App\Kernel
                bootstrap: features/bootstrap/bootstrap.php
        FriendsOfBehat\CrossContainerExtension: ~
        FriendsOfBehat\ContextServiceExtension:
            imports:
               - "features/bootstrap/Resources/config/services.xml"
```

**features/bootstrap/bootstrap.php** (the one used by official Behat Symfony extension)
```php
<?php

use Symfony\Component\Dotenv\Dotenv;

// The check is to ensure we don't use .env in production
if (!isset($_SERVER['APP_ENV'])) {
    if (!class_exists(Dotenv::class)) {
        throw new \RuntimeException('APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file.');
    }
    (new Dotenv())->load(__DIR__ . '/../../.env.travis');
}
```

**.env.travis**
```
###> symfony/framework-bundle ###
APP_ENV=test
APP_SECRET=42ea61e1f4e974a5513972ad2fdeed74
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

# ...
```

**features/bootstrap/Resources/config/services.xml**
```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <defaults public="true" autoconfigure="true"/>

        <service id="features.definitions.user" class="Features\Definitions\UserDefinition">
            <argument type="service" id="__symfony__.test.App\Manager\UserManager"/>
            <tag name="fob.context_service" />
        </service>
    </services>
</container>
```

**config/services.yml**
```yml
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true     
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'
```

**config/services_test.yml**
```yml
services:
    _defaults:
        public: true

    test.App\Manager\UserManager: '@App\Manager\UserManager'
```

</details>
<br/>

Also, I tried some `dump` in the code and I found some strange things.

```diff
--- KernelBasedContainerAccessor_Original.php	2018-01-24 20:52:22.774915294 +0100
+++ KernelBasedContainerAccessor.php	2018-01-24 20:50:51.207708272 +0100
@@ -28,6 +28,7 @@
      */
     public function __construct(KernelInterface $kernel)
     {
+        dump($kernel);
         $this->kernel = $kernel;
     }
 
@@ -36,6 +37,7 @@
      */
     public function getService(string $id)
     {
+        dump($this->kernel);
         $container = $this->kernel->getContainer();
 
         if (!$container instanceof Container) {
```

The 1st `dump` is displaying (**twice ??**) my `App\Kernel` (booted), as expected:

<details>
  <summary>Click to expand</summary>
 

```
App\Kernel {#708
  #bundles: array:10 [
    "FrameworkBundle" => Symfony\Bundle\FrameworkBundle\FrameworkBundle {#711
      #name: "FrameworkBundle"
      #extension: null
      #path: null
      -namespace: "Symfony\Bundle\FrameworkBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "DoctrineCacheBundle" => Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle {#712
      #name: "DoctrineCacheBundle"
      #extension: null
      #path: null
      -namespace: "Doctrine\Bundle\DoctrineCacheBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "DoctrineBundle" => Doctrine\Bundle\DoctrineBundle\DoctrineBundle {#713
      -autoloader: Closure {#838
        class: "Doctrine\Common\Proxy\Autoloader"
        parameters: {
          $className: {}
        }
        use: {
          $proxyDir: "/var/cache/app/test/doctrine/orm/Proxies"
          $proxyNamespace: "Proxies"
          $notFoundCallback: Closure {#839 …}
        }
        file: "./vendor/doctrine/common/lib/Doctrine/Common/Proxy/Autoloader.php"
        line: "80 to 90"
      }
      #name: "DoctrineBundle"
      #extension: null
      #path: null
      -namespace: "Doctrine\Bundle\DoctrineBundle"
      #container: & ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "DoctrineMigrationsBundle" => Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle {#714
      #name: "DoctrineMigrationsBundle"
      #extension: null
      #path: null
      -namespace: "Doctrine\Bundle\MigrationsBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "StofDoctrineExtensionsBundle" => Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle {#715
      #name: "StofDoctrineExtensionsBundle"
      #extension: null
      #path: null
      -namespace: "Stof\DoctrineExtensionsBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "SecurityBundle" => Symfony\Bundle\SecurityBundle\SecurityBundle {#716
      #name: "SecurityBundle"
      #extension: null
      #path: null
      -namespace: "Symfony\Bundle\SecurityBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "WebProfilerBundle" => Symfony\Bundle\WebProfilerBundle\WebProfilerBundle {#717
      #name: "WebProfilerBundle"
      #extension: null
      #path: null
      -namespace: "Symfony\Bundle\WebProfilerBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "TwigBundle" => Symfony\Bundle\TwigBundle\TwigBundle {#718
      #name: "TwigBundle"
      #extension: null
      #path: null
      -namespace: "Symfony\Bundle\TwigBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "OverblogGraphQLBundle" => Overblog\GraphQLBundle\OverblogGraphQLBundle {#719
      #name: "OverblogGraphQLBundle"
      #extension: null
      #path: null
      -namespace: "Overblog\GraphQLBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
    "LexikJWTAuthenticationBundle" => Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle {#720
      #name: "LexikJWTAuthenticationBundle"
      #extension: null
      #path: null
      -namespace: "Lexik\Bundle\JWTAuthenticationBundle"
      #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
    }
  ]
  #container: ContainerXpEPRn2\srcTestDebugProjectContainer {#840 …17}
  #rootDir: "/srv/app/src"
  #environment: "test"
  #debug: true
  #booted: true
  #name: "src"
  #startTime: 1516823421.3279
  -projectDir: "/srv/app"
  -warmupDir: null
  -requestStackSize: 0
  -resetServices: false
}
```
</details>
<br/>

But the second `dump` call  is displaying a no-booted `App\Kernel`:
```
App\Kernel {#960
  #bundles: []
  #container: null
  #rootDir: "/srv/app/src"
  #environment: "test"
  #debug: true
  #booted: false
  #name: "src"
  #startTime: 1516823748.7259
  -projectDir: null
  -warmupDir: null
  -requestStackSize: 0
  -resetServices: false
}
```

So I tried to boot it manually like this:

```diff
--- KernelBasedContainerAccessor_Original.php	2018-01-24 20:52:22.774915294 +0100
+++ KernelBasedContainerAccessor.php	2018-01-24 20:58:49.359231205 +0100
@@ -36,6 +36,8 @@
      */
     public function getService(string $id)
     {
+        $this->kernel->boot();
+        dump($this->kernel);
         $container = $this->kernel->getContainer();
 
         if (!$container instanceof Container) {
```

And it's dumping my booted `App\Kernel`, with a working **container**!! :smile: 

But, I don't think my solution is the good solution. 
It must have a reason why it's not working as expected, can you take a look please? 
Thanks :smiley:
